(deftheme material-light-custom
  "Created 2018-07-21.")

(custom-theme-set-variables
 'material-light-custom
 '(ansi-color-names-vector ["#212121" "#B71C1C" "#558b2f" "#FFA000" "#2196f3" "#4527A0" "#00796b" "#FAFAFA"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'material-light-custom
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#00796b" :bold t))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#2196f3" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#607d8b"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#212121" :background "#EFEBE9"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#212121" :background "#EFEBE9"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#ECEFF1"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#80cbc4" :underline t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#00796b" :height 1.35))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#558b2f" :height 1.35))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#212121" :height 1.35))))
 '(org-done ((((class color) (min-colors 89)) (:background "#c8e6c9" :bold t :foreground "#2e7d32"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#607d8b"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#00796b"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#B71C1C"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#FAFAFA" :background "#FAFAFA"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#B71C1C" :underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#FF5722"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#607d8b"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#1565c0" :background "#e0f7fa"))))
 '(org-todo ((((class color) (min-colors 89)) (:background "#ffcdd2" :bold t :foreground "#c62828"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#FF5722"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#B71C1C"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#4e342e" :background "#efebe9" :box (:style released-button)))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:foreground "#4e342e" :background "#efebe9" :box (:style released-button)))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit outline-1 :background "#cfd8dc" :weight bold :box (:style released-button) :height 1.3))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit outline-2 :background "#C8E6C9" :box (:style released-button) :height 1.2))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit outline-3 :height 1.1))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit outline-4 :height 1.0))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit outline-5))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit outline-6))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit outline-7))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit outline-8)))))
(provide 'iris-material-org-theme-light)
