;; desctibe-theme可将主题另存,可以修改相关设置,以及方便的将不同主题需要的部分结合
;; list-faces-display可以修改样式,可将修改好的样式补充到该文件
;; org及font-lock取自leuven-theme,其中orgmode的一二三级标题分别为1.3,1.2,1.1
;; fringe是buffer两边一小段宽度的颜色
;; 将helm的文件及目录的背景换成了其它颜色
;; helm-match及helm-match-item更改
;; helm-candidate-number修改
;; mode-line及powerline修改


(custom-theme-set-variables
 'spacemacs-light
 '(ansi-color-names-vector ["#d2ceda" "#f2241f" "#67b11d" "#b1951d" "#3a81c3" "#a31db1" "#21b8c7" "#655370"]))

(custom-theme-set-faces
 'spacemacs-light
 '(fringe ((((class color) (min-colors 89)) (:background "#EAEAFA" :foreground "#655370"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#006FE0"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#8D8D84"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:slant italic :foreground "#8D8D84"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#D0372D"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#036A07"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#006699"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold nil :foreground "#0000FF"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#808080"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#008000"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:weight normal :foreground "#6434A3"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#BA36A5"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "red"))))
 '(helm-bookmark-directory ((((class color) (min-colors 89)) (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(helm-bookmark-gnus ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(helm-bookmark-info ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(helm-bookmark-man ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(helm-bookmark-w3m ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#655370" :background "#FFEDED"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "#655370" :background "#FFEDED"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#6c4173" :background "#FFEDED"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#FFEDED"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "#655370" :background "#FFEDED"))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#655370" :background "#FFEDED"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:background "#FFFFFF" :foreground "#3a81c3" :inherit bold))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#FFEDED" :inherit bold))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#FFEDED" :inherit bold))))
 '(helm-ff-dotted-symlink-directory ((((class color) (min-colors 89)) (:foreground "#21b8c7" :background "#FFEDED" :inherit bold))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#42ae2c" :background "#FFEDED" :weight normal))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#655370" :background "#FFEDED" :weight normal))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#FFEDED" :inherit bold))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:foreground "#FFEDED" :background "#3a81c3" :weight normal))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#21b8c7" :background "#FFEDED" :inherit bold))))
 '(helm-grep-cmd-line ((((class color) (min-colors 89)) (:foreground "#655370" :background "#FFEDED"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#655370" :background "#FFEDED"))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#655370" :background "#FFEDED"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#ba2f59" :background "#FFEDED" :inherit bold))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit helm-match))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#655370" :background "#FFEDED" :underline nil :box nil))))
 '(helm-header-line-left-margin ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background nil))))
 '(helm-match ((((class color) (min-colors 89)) (:background "#FFD1C9" :foreground "#6C4173"))))
 '(helm-match-item ((((class color) (min-colors 89)) (:background "#FFD1C9" :foreground "#6C4173"))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#715ab1" :background "#FFEDED"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#efeae9"))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#6c4173" :background "#FFEDED"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#6c4173" :foreground "#FFEDED" :inherit bold))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#e3dedd"))))
 '(mode-line ((t (:background "white" :foreground "#655370" :box (:line-width 1 :color "#b3b9be")))))
 '(mode-line-inactive ((t (:background "white" :foreground "#655370" :box (:line-width 1 :color "#b3b9be")))))
 '(powerline-active1 ((t (:background "#BCBCE0" :foreground "#655370"))))
 '(powerline-active2 ((t (:background "#BCBCE0" :foreground "#655370"))))
 '(powerline-inactive1 ((t (:background "white" :foreground "#655370"))))
 '(powerline-inactive2 ((t (:background "white" :foreground "#655370"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#333333" :background "#FFFFFF"))))
 )

;; org-mode from spacemacs-light-theme
(custom-set-faces
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:background "#d3d3e7" :foreground "#6c4173"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#715ab1" :height 1.0))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold :height 1.0))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit bold :foreground "#715ab1"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#42ae2c" :height 1.0))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:inherit bold :foreground "#6c4173"))))
 '(org-block ((((class color) (min-colors 89)) (:background "#e8e3f0" :foreground "#655370"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:background "#ddd8eb" :foreground "#9380b2"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:background "#ddd8eb" :foreground "#9380b2"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#21b8c7"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#715ab1"))))
 '(org-date-selected ((((class color) (min-colors 89)) (:background "#6c3163" :foreground "#fbf8ef"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#da8b55"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#6c3163" :inherit bold :height 1.4 :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#42ae2c" :inherit bold :background "#edf2e9"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#655370"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit bold :foreground "#3a81c3" :height 1.3 :background nil))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit bold :foreground "#2d9574" :height 1.2 :background nil))))
 '(org-level-3 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d" :height 1.1 :background nil))))
 '(org-level-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d" :background nil))))
 '(org-level-5 ((((class color) (min-colors 89)) (:bold nil :foreground "#3a81c3"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:bold nil :foreground "#2d9574"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d"))))
 '(org-link ((((class color) (min-colors 89)) (:underline t :foreground "#2aa1ae"))))
 '(org-meta-line ((((class color) (min-colors 89)) (:foreground "#da8b55"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(org-priority ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(org-quote ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#6c3163" :height 1.0))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#655370" :slant italic))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#655370" :background "#edf1ed"))))
 '(org-tag ((((class color) (min-colors 89)) (:foreground "#da8b55"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold :background "#f6f1e1"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit org-priority))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(org-verse ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit org-priority)))))

(provide 'iris-theme)
