(deftheme material-light-for-custom
  "Created 2018-07-21.")

(custom-theme-set-variables
 'material-light-for-custom
 '(ansi-color-names-vector ["#212121" "#B71C1C" "#558b2f" "#FFA000" "#2196f3" "#4527A0" "#00796b" "#FAFAFA"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'material-light-for-custom
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#B71C1C"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#607d8b"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#607d8b"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#673ab7"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#0097A7"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#00796b"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#FFA000"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#FFA000"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#4527A0"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#689f38"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#0097A7"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#EF6C00"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#B71C1C"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#607d8b"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#B71C1C"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#FF5722"))))
 '(avy-background-face ((((class color) (min-colors 89)) (:foreground "#cfd8dc" :weight normal))))
 '(avy-lead-face-0 ((((class color) (min-colors 89)) (:foreground "#FAFAFA" :background "#558b2f" :weight bold))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:foreground "#FAFAFA" :background "#558b2f" :weight bold))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#B71C1C")))))
 '(flycheck-info ((((class color) (min-colors 89)) (:underline (:style wave :color "#2196f3")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#FF5722")))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#B71C1C" :background "#ECEFF1"))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#2196f3" :background "#ECEFF1"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#FFA000" :background "#ECEFF1"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#e91e63"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#1565C0"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#EF6C00"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#B388FF"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#76ff03"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#26A69A"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#B71C1C"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#795548"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#827717"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#212121" :background "#EF6C00"))))
 '(mmm-code-submode-face ((((class color) (min-colors 89)) (:background "#ECEFF1"))))
 '(mmm-comment-submode-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mmm-output-submode-face ((((class color) (min-colors 89)) (:background "#ECEFF1"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#FAFAFA" :background "#558b2f" :inverse-video nil))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#FAFAFA" :background "#558b2f"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#FAFAFA" :inherit font-lock-warning-face :inverse-video t))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#FF5722"))))
 '(anzu-replace-highlight ((((class color) (min-colors 89)) (:inherit isearch-lazy-highlight-face))))
 '(anzu-replace-to ((((class color) (min-colors 89)) (:inherit isearch))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#FFA000" :weight bold :underline nil))))
 '(cursor ((((class color) (min-colors 89)) (:background "#FF5722"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#ECEFF1"))))
 '(border ((((class color) (min-colors 89)) (:background "#ECEFF1"))))
 '(vertical-border ((((class color) (min-colors 89)) (:background "#90A4AE" :foreground "#90A4AE"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#ECEFF1"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#212121" :background "#e0f7fa" :box (:line-width 2 :color "#ECEFF1")))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#212121" :background nil :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#a7adba" :background "#ECEFF1" :weight normal))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#212121" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#4527A0" :box nil))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(region ((((class color) (min-colors 89)) (:background "#90A4AE"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#bf616a"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#4527A0" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "#B71C1C" :inverse-video t :underline nil))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:foreground "#B71C1C" :inverse-video t :underline nil))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:foreground "#B71C1C" :inverse-video t :underline nil))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:foreground "#B71C1C" :inverse-video t :underline nil))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:foreground "#B71C1C" :inverse-video t :underline nil))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background nil :foreground "#B71C1C"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background nil :foreground "#00796b"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background nil :foreground "#90A4AE"))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background nil :foreground "#90A4AE"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background nil :foreground "#90A4AE"))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background nil :foreground "#90A4AE"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:background "#558b2f" :foreground "#558b2f"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:background "#2196f3" :foreground "#2196f3"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:background "#FF5722" :foreground "#FF5722"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#FF5722"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#00796b" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#4527A0"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:inherit diff-added :inverse-video t))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:inherit diff-removed :inverse-video t))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#558b2f" :weight bold))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#212121"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#558b2f" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#B71C1C"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#FFA000"))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t :weight bold))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#ECEFF1" :box (:line-width 1 :color "#212121")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#FFA000"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#FFA000"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#B71C1C"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#212121" :background "#FAFAFA"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#ECEFF1"))))
 '(helm-match ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#212121"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#00796b"))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#4527A0"))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#00796b"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "#212121"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#00796b" :underline t))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#B71C1C"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#FF5722"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#FAFAFA" :background "#00796b"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#C8E6C9" :foreground "#424242" :height 1.3 :bold t))))
 '(guide-key/key-face ((((class color) (min-colors 89)) (:foreground "#212121"))))
 '(guide-key/highlight-command-face ((((class color) (min-colors 89)) (:foreground "#FF5722"))))
 '(guide-key/prefix-command-face ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#607d8b" :background "#cfd8dc"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#607d8b" :background "#cfd8dc"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#F0F0F0"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#C0C0C0"))))
 '(company-template-field ((((class color) (min-colors 89)) (:background "#cfd8dc"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:weight bold :foreground "#607d8b" :background "#cfd8dc"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:weight normal :foreground "#607d8b" :background "#cfd8dc"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip-selection))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip-selection))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:weight bold :foreground "#212121" :background "#e0f7fa"))))
 '(powerline-active1 ((t (:foreground "#212121" :background "#cfd8dc"))))
 '(powerline-active2 ((t (:foreground "#212121" :background "#cfd8dc"))))
 '(powerline-inactive1 ((t (:foreground "#607d8b" :background "#90A4AE"))))
 '(powerline-inactive2 ((t (:foreground "#607d8b" :background "#90A4AE"))))
 '(spaceline-python-venv ((t (:foreground "#00796b"))))
 '(spaceline-evil-normal ((t (:foreground "#FAFAFA" :background "#FFA000" :inherit mode-line))))
 '(spaceline-evil-insert ((t (:foreground "#FAFAFA" :background "#558b2f" :inherit mode-line))))
 '(spaceline-evil-visual ((t (:foreground "#FAFAFA" :background "#90A4AE" :inherit mode-line))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#2196f3"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#558b2f"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#212121" :background "#FAFAFA")))))

(provide-theme 'material-light-for-custom)
