(deftheme material-for-custom
  "Created 2018-07-21.")

(custom-theme-set-variables
 'material-for-custom
 '(ansi-color-names-vector ["#ffffff" "#f36c60" "#8bc34a" "#fff59d" "#4dd0e1" "#b39ddb" "#81d4fa" "#263238"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'material-for-custom
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#ff8A65"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#84ffff"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#b39ddb"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#9ccc65"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#84ffff"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#ffcc80"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#f36c60"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(avy-background-face ((((class color) (min-colors 89)) (:foreground "#78909c" :weight normal))))
 '(avy-lead-face-0 ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#ef6c00" :weight bold))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#ef6c00" :weight bold))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#f36c60")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#ff9800")))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#e91e63"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#2196F3"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#EF6C00"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#B388FF"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#76ff03"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#26A69A"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#FFCDD2"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#795548"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#DCE775"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#EF6C00"))))
 '(mmm-code-submode-face ((((class color) (min-colors 89)) (:background "#37474f"))))
 '(mmm-comment-submode-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mmm-output-submode-face ((((class color) (min-colors 89)) (:background "#37474f"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#263238" :background "#8bc34a" :inverse-video nil))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#8bc34a"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#263238" :inherit font-lock-warning-face :inverse-video t))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(anzu-replace-highlight ((((class color) (min-colors 89)) (:inherit isearch-lazy-highlight-face))))
 '(anzu-replace-to ((((class color) (min-colors 89)) (:inherit isearch))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#fff59d" :weight bold :underline nil))))
 '(cursor ((((class color) (min-colors 89)) (:background "#ff9800"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#263238"))))
 '(border ((((class color) (min-colors 89)) (:background "#37474f"))))
 '(vertical-border ((((class color) (min-colors 89)) (:background "#555555" :foreground "#555555"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#37474f"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#1c1f26"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#ffffff" :background nil :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#a7adba" :background "#1c1f26" :weight normal :box nil))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#ffffff" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#b39ddb" :box nil))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(region ((((class color) (min-colors 89)) (:background "#555555"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#bf616a"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#b39ddb" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "#f36c60" :inverse-video t :underline nil))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:foreground "#f36c60" :inverse-video t :underline nil))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:foreground "#f36c60" :inverse-video t :underline nil))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:foreground "#f36c60" :inverse-video t :underline nil))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:foreground "#f36c60" :inverse-video t :underline nil))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background nil :foreground "#f36c60"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background nil :foreground "#81d4fa"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background nil :foreground "#555555"))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background nil :foreground "#555555"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background nil :foreground "#555555"))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background nil :foreground "#555555"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:background "#8bc34a" :foreground "#8bc34a"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:background "#81d4fa" :foreground "#81d4fa"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:background "#ff9800" :foreground "#ff9800"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#81d4fa"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#81d4fa" :background nil))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#4dd0e1" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#b39ddb"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:inherit diff-added :inverse-video t))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:inherit diff-removed :inverse-video t))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#8bc34a" :weight bold))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#8bc34a" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t :weight bold))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#37474f" :box (:line-width 1 :color "#ffffff")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#263238"))))
 '(helm-match ((((class color) (min-colors 89)) (:foreground "gold1"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#37474f"))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#b39ddb"))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#81d4fa" :underline t))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#ef6c00"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#455A64" :foreground "#eceff1" :height 1.3 :bold t))))
 '(guide-key/key-face ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(guide-key/highlight-command-face ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(guide-key/prefix-command-face ((((class color) (min-colors 89)) (:foreground "#81d4fa"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#b0bec5" :background "#78909c"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#b0bec5" :background "#78909c"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#F0F0F0"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#C0C0C0"))))
 '(company-template-field ((((class color) (min-colors 89)) (:background "#78909c"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:weight bold :foreground "#1c1f26" :background "#78909c"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:weight normal :foreground "#b0bec5" :background "#78909c"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip-selection))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip-selection))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#37474f"))))
 '(powerline-active1 ((t (:foreground "#ffffff" :background "#555555"))))
 '(powerline-active2 ((t (:foreground "#ffffff" :background "#78909c"))))
 '(powerline-inactive1 ((t (:foreground "#b0bec5" :background "#555555"))))
 '(powerline-inactive2 ((t (:foreground "#b0bec5" :background "#555555"))))
 '(spaceline-python-venv ((t (:foreground "#fff59d"))))
 '(spaceline-evil-normal ((t (:foreground "#ffffff" :background "#ff9800" :inherit mode-line))))
 '(spaceline-evil-insert ((t (:foreground "#263238" :background "#8bc34a" :inherit mode-line))))
 '(spaceline-evil-visual ((t (:foreground "#ffffff" :background "#555555" :inherit mode-line))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#263238")))))

(provide-theme 'material-for-custom)
